
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Za Warudo! Toki Wo Tomatta...",
    [2] = "All"
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))


wait()

local args = {
    [1] = "Boombox",
    [2] = "4523066727"
}

game:GetService("ReplicatedStorage").MainEvent:FireServer(unpack(args))

wait(0.1)

local args = {
    [1] = "wear",
    [2] = 4783451427
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()


local args = {
    [1] = "wear",
    [2] = 29532363
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()

local args = {
    [1] = "wear",
    [2] = 4238305136
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()


local args = {
    [1] = "wear",
    [2] = 4484503762
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()


local args = {
    [1] = "wear",
    [2] = 6070552935
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()


local args = {
    [1] = "wear",
    [2] = 5266543827
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait()


local args = {
    [1] = "wear",
    [2] = 6105248989
}

game:GetService("ReplicatedStorage").Catalog.Body.LeftLegs.UnU:FireServer(unpack(args))

wait(2.9)

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "BoomboxStop"
}

game:GetService("ReplicatedStorage").MainEvent:FireServer(unpack(args))




--   Dio avatar code's 
-- ______________________
--| 4783451427 - jacket  |
--| 29532363 - face      |
--| 4238305136 - menacing|
--| 4484503762 - headband|
--|  6070552935 - cape   |
--| 5266543827 - pants   |
--|  6105248989 - hair   |
-- ￣￣￣￣￣￣￣￣￣￣￣￣￣ 
